language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install --use-mirrors psutil python-daemon"
# command to run tests
script:
  - nosetests
  - python setup.py test

